### ISSUE TITLE
I don't understand how to use this API

### ISSUE THREAD

**Issue by harshascode** [koikiss-dev/jimov_api#163]
Can you guys make a proper document or video tutorial? Your docs lack information and guidance for beginners.

**Comment by barrientosvctor** [comment]
Hello harshascode, thanks for creating an issue. What type of information do you think is missing?

**Comment by harshascode** [comment]
Sorry, I'm a little confused in api endpoint.

**Comment by koikiss-dev** [comment]
Hello, can you give us more details to improve the documentation? The base route is here "The initial route is as follows JIMOV"
 https://jimov-api-docs.vercel.app/introduction/getting-started#:~:text=The%20initial%20route%20is%20as%20follows%20JIMOV

**Comment by barrientosvctor** [comment]
Closed due to inactivity.
