### ISSUE TITLE
big problem with [(animelatinohd.com) in api.animelatinohd.com] require referer now

### ISSUE THREAD

**Issue by TokyoTF** [koikiss-dev/jimov_api#89]
it is most possible that they became aware of the project and right now I'm thinking of a solution to the issue.

![image](https://github.com/koikiss-dev/jimov_api/assets/52444606/cd4fddde-49cb-4bc8-909e-609ba26409bd)
![image](https://github.com/koikiss-dev/jimov_api/assets/52444606/7230491a-1395-4b39-b945-69b47601559b)

**Comment by koikiss-dev** [comment]
Problem on any route? Currently working fine
![image](https://github.com/koikiss-dev/jimov_api/assets/48816029/6c566c1e-b60a-4fea-b12c-3d0a0547955a)

**Comment by TokyoTF** [comment]
the problem is that you can't access the url not the JIMOV api example https://api.animelatinohd.com/stream/258340

**Comment by elRubenof** [comment]
Is there any way to access the "api.animelatinohd.com/stream/xxxxxx" urls at the moment? Also from postman or other ways to try to implement in my project that uses jimov until it is solved.

**Comment by TokyoTF** [comment]
Unfortunately they changed all the state of their api requiring referer to be used with this and no one except them can use it, the solution is to scraper the direct page, soon it will be updated.😓
