### ISSUE TITLE
Add New Providers

### ISSUE THREAD

**Issue by OshekharO** [koikiss-dev/jimov_api#9]
Movies:

1. https://prmovies.help
2. https://movie-web.app
3. https://desicinemas.tv
4. https://fmovies.to

Animes:

1. https://m.wcostream.net
2. https://animepahe.ru
3. https://www.animerush.tv (down)

Manga:

1. https://manganato.com 
2. https://comick.app (api) (ok)
3. https://w14.mangafreak.net
6. https://mangabuddy.com
7. https://readcomicsfree.net
8. https://viewcomics.me
9. https://getcomics.info
10. https://comicastle.org
11. https://mangapill.com  (wait)
12. https://mangareader.to (ok)

Light Novel:

1. https://mtlnation.com
2. https://novelsemperor.com
3. https://www.mtlnovel.com
4. https://www.readwn.com
5. https://ranobes.net
6. https://novelup.plus

Check these recommendations, when you get the time.

**Comment by koikiss-dev** [comment]
**Thanks!**

**Comment by Mawfyy** [comment]
Perfect, we look this

**Comment by Zukaritasu** [comment]
Excelent

**Comment by TokyoTF** [comment]
(https://animepahe.ru) - all videos are hosted by private and they can only be seen on the page of origin, that is, animepahe

Wait to create schematic(Movies and Light Novel)
